DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    LAST_NAME VARCHAR NOT NULL,
    AGE INT NOT NULL,
    DATE_BIRTH DATE NOT NULL
);

